- name:
  hosts: local
  connection: local
  vars:
    course: ansible  #$VAR or ${VAR} in shell
    started: may
  tasks:
  - name: print course information
    ansible.builtin.debug:
      msg: "Hello {{course}}, Course Started at {{started}}"  # keep these values in variables should be in double quotes