- name: vars with preference
  hosts: local
  connection: local
  vars:
    greeting: "hello from play"
  vars_files: 
    - course.yaml
  vars_prompt:
    - name: greeting
      prompt: please enter greeting
      private: false
  tasks:
  - name: print the greeting 
    vars: 
      greeting: "hello from task"
    ansible.builtin.debug:
      msg: "{{greeting}}"