- name: ansible datatypes
  hosts: local
  connection: local
  vars:
    duration: 1.2HR #This is number
    course: "DevOps with AWS" #String
    is_live: true #boolean
    tools: #List
    - Linux
    - shell
    - ansible
    concepts: #map or dictionoary in python (Key: value) reffered like braces 
      CI: jenkins
      scripting: "shell, ansible"
  tasks:
    - name: print course information
      ansible.builtin.debug:
       msg: "Course is: {{ course }}, Duration: {{ duration }}, is live?: {{ is_live }}, Tools are: {{ tools }}, Concepts are: {{ concepts }}"
