- name: anisible with functions
  hosts: local
  connection: local
  vars:
    persons: "Uma,Tarak,sunil"
  tasks:
  - name: checking default functions
    ansible.builtin.debug:
      msg: "hello, {{ person | default('Uma') }}"  # If value of any varaible is not defined then we can use default function
  - name: print names 
    ansible.builtin.debug:
      msg: "hello, {{ persons | split(',') }}"  # spliting the string
  - name: convert map to list
    vars: 
      course: 
        name: ansible
        duration: 120HR
    ansible.builtin.debug:
      msg: "course info: {{course | dict2items }}"
  - name: check whether Ip address is valid or not 
    vars: 
      ip: 234.345.678.234
    ansible.builtin.debug:
      msg: "is {{ ip | ansible.utils.ipaddr}}"  