- name: anisible with functions
  hosts: local
  connection: local
  tasks:
  - name: checking default functions
    ansible.builtin.debug:
      msg: "hello, {{ person | default(Uma)}}"  # If value of any varaible is not defined then we can use default function