- name: shell Vs command
  hosts: frontend 
  tasks: 
  - name: redirecting the output file
    #ansible.builtin.command: "ls -ltr > /tmp/output.txt"
    ansible.builtin.shell: "ls -ltr > /tmp/output.txt"
    register: command_result #to store the output

  - name: print the outcome
    ansible.builtin.debug:
      msg: "{{ command_result }}"
      
  - name: not redirecting the output file
    #ansible.builtin.command: "ls -ltr "
    register: command_result #to store the output

  - name: print the outcome
    ansible.builtin.debug:
      msg: "{{ command_result }}"